/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProjectSummary {
  slug: string
  memoryDir: string
  indexPresent: boolean
  memoryCount: number
}
export interface MemorySummary {
  slug: string
  fileName: string
  title: string
  description?: string
  type?: string
  modified?: string
  mtimeMs: number
  sizeBytes: number
  indexed: boolean
  indexHook?: string
}
export interface MemoryDetail {
  slug: string
  fileName: string
  title: string
  description?: string
  type?: string
  modified?: string
  mtimeMs: number
  sizeBytes: number
  indexed: boolean
  indexHook?: string
  body: string
  frontmatterRaw?: string
  raw: string
}
export interface ListMemoriesResult {
  indexRaw: string
  entries: Array<MemorySummary>
}
export interface SearchHit {
  project: string
  slug: string
  field: string
  line: number
  snippet: string
}
export interface WriteResult {
  slug: string
  indexUpdated: boolean
}
export interface DeleteResult {
  slug: string
  fileDeleted: boolean
  indexLinesRemoved: number
}
export interface CreateMemoryInput {
  slug: string
  name?: string
  description?: string
  type?: string
  body: string
}
export interface UpdateMemoryInput {
  content?: string
  name?: string
  description?: string
  type?: string
  body?: string
  syncIndex?: boolean
}
export declare function listProjects(root: string): Promise<Array<ProjectSummary>>
export declare function listMemories(root: string, project: string): Promise<ListMemoriesResult>
export declare function readMemory(root: string, project: string, slug: string): Promise<MemoryDetail>
export declare function searchMemories(root: string, query: string, project?: string | undefined | null): Promise<Array<SearchHit>>
export declare function createMemory(root: string, project: string, input: CreateMemoryInput): Promise<WriteResult>
export declare function updateMemory(root: string, project: string, slug: string, input: UpdateMemoryInput): Promise<WriteResult>
export declare function deleteMemory(root: string, project: string, slug: string): Promise<DeleteResult>
